# This workflow is to showcase how to use a manual workflow to trigger a job

name: Manual and Schedule Task
on:
  workflow_dispatch: # This is required when creating a workflow that leverages GitHub actions
    inputs:
      tag:
        description: "The value of the tag to use"
        required: true
        default: "Test value"
      another_tag:
        description: "Something funny"
        required: false
        default: "Smitty Werben Jager Man Jensen"
  #schedule: # Creating a chron job along with the manual workflow (runs every 5 mins)
  #  - cron: "*/5 * * * *"

jobs:
  test_manual:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}

    outputs:
      job_output: ${{ steps.echo.outputs.job_output }}

    steps:
      - name: Echo Hello World
        id: echo
        run: |
          echo "Tag Value ${{ github.event.inputs.tag }}"

          echo "You are identified as ${{ github.event.inputs.another_tag }}"

          echo "::set-output name=job_output::${{ github.event.inputs.another_tag }}"
  
  test_schedule:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Automated Task
        run: |
          echo "This is an automated step! Hello there!"