
name: terraform-fmt

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
    branches:
      - master
  push:
    branches:
    - master

jobs:
  lintv12:
    name: terraform-fmt-v12
    runs-on: ubuntu-latest
    container:
      # Using v0.12.24
      image: hashicorp/terraform@sha256:53fb1c0a78c8bb91c4a855c1b352ea7928f6fa65f8080dc7a845e240dd2a9bee

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH }}
    - name: Lint terraform
      run: |
        cd $GITHUB_WORKSPACE
        for d in $(find . -type d \( -not -path '**/.terraform*/**' -and -path './env/**' -or -path './modules/**' \) -exec sh -c '(ls -p "{}"|grep />/dev/null)||echo "{}"' \; | sort); do
          terraform fmt -check -recursive -diff $d
        done