name: PR Inputs
on:
  pull_request: # PR pushes or when a PR merges
    types:
      - synchronize
      - opened
      - reopened
      - closed
    branches:
      - master
    paths:
      -'scripts/**'

jobs:

  tester:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"