name: tfsec
on:
  pull_request:
      paths:
        - '**.tf'
      branches:
        - master
  push:
    branches:
      - master
    paths:
      - '**.tf'

jobs:
  on_push_verify:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Security
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}